sudo: false
addons:
    apt_packages:
        - lib32stdc++6

env:
    - SMVERSION=1.7
    - SMVERSION=1.8
    - SMVERSION=1.9
    
install:
    - mkdir build && cd build
    - wget "http://www.sourcemod.net/latest.php?version=$SMVERSION&os=linux" -O sourcemod-$SMVERSION-linux.tar.gz
    - tar -xzf sourcemod-$SMVERSION-linux.tar.gz
before_script:
    - cd addons/sourcemod/scripting/
    - chmod +x spcomp
script: ./compile.sh ./scripting/retake_overlays.sp

notifications:
    email: false